
# ═══════════════════════════════════════════════════════════════
# 🚀 Generated by GitMaxer (Free Plan)
# 🔗 Upgrade at https://gitmaxer.vercel.app for watermark-free code
# ═══════════════════════════════════════════════════════════════

-- This tutorial will teach you how to combine and filter data
-- from multiple extraterrestrial species' logs using SQL JOIN and WHERE clauses.
-- By the end of this tutorial, you will be able to:
-- 1. Understand the purpose of JOIN operations in SQL.
-- 2. Combine data from different tables based on common fields.
-- 3. Filter the combined data using conditions.
-- 4. Apply these concepts to a practical scenario of decoding alien messages.

-- Let's imagine we have logs from three different alien species:
-- The Arcturians, the Sirians, and the Pleiadians.
-- Each species records different types of information, but they all refer to common astronomical events or entities.

-- First, we'll create some sample tables to represent these alien logs.
-- In a real-world scenario, these tables would already exist in a database.

-- Table for Arcturian Log Entries
-- Stores general observations and celestial body designations.
CREATE TABLE ArcturianLog (
    log_id INT PRIMARY KEY AUTO_INCREMENT, -- Unique identifier for each log entry.
    timestamp DATETIME,                   -- When the observation was recorded.
    celestial_body_designation VARCHAR(100), -- The name or code for a star, planet, etc.
    observation_notes TEXT                 -- Detailed notes from the Arcturians.
);

-- Table for Sirian Communication Transcripts
-- Stores deciphered fragments of inter-species communication, linked by event IDs.
CREATE TABLE SirianTranscript (
    transcript_id INT PRIMARY KEY AUTO_INCREMENT, -- Unique identifier for each transcript.
    event_timestamp DATETIME,                     -- The time of the event being communicated about.
    communication_fragment VARCHAR(255),          -- A piece of the deciphered message.
    sender_species VARCHAR(50)                    -- The species sending the communication.
);

-- Table for Pleiadian Stellar Cartography Data
-- Stores information about specific star systems and their characteristics,
-- which can be cross-referenced with other logs by system name.
CREATE TABLE PleiadianStarChart (
    star_chart_id INT PRIMARY KEY AUTO_INCREMENT, -- Unique identifier for each star chart entry.
    system_name VARCHAR(100),                      -- The name of the star system.
    primary_star_type VARCHAR(50),                 -- The type of the main star in the system.
    number_of_planets INT                          -- How many planets are in this system.
);

-- Now, let's populate these tables with some hypothetical alien data.
-- This data will simulate the logs we need to decode.

-- Inserting sample data into ArcturianLog
INSERT INTO ArcturianLog (timestamp, celestial_body_designation, observation_notes) VALUES
('2023-10-26 10:00:00', 'Alpha Centauri', 'Noted unusual energy readings.'),
('2023-10-26 11:00:00', 'Sirius B', 'Observed faint stellar activity.'),
('2023-10-26 12:00:00', 'Proxima Centauri', 'Potential habitable zone identified.'),
('2023-10-27 09:00:00', 'Vega', 'Fascinating spectral signature detected.'),
('2023-10-27 10:00:00', 'Alpha Centauri', 'Energy readings are stabilizing.');

-- Inserting sample data into SirianTranscript
INSERT INTO SirianTranscript (event_timestamp, communication_fragment, sender_species) VALUES
('2023-10-26 10:00:00', 'Warning: Gravitational anomaly detected.', 'Pleiadian'),
('2023-10-26 11:00:00', 'Encountered new entity near Sirius B.', 'Arcturian'),
('2023-10-26 12:00:00', 'Exploration of Proxima Centauri system is proceeding.', 'Sirian'),
('2023-10-27 09:00:00', 'Spectra analysis from Vega matches ancient archives.', 'Arcturian'),
('2023-10-27 11:00:00', 'Unusual signal originating from the Orion Arm.', 'Unknown');

-- Inserting sample data into PleiadianStarChart
INSERT INTO PleiadianStarChart (system_name, primary_star_type, number_of_planets) VALUES
('Alpha Centauri', 'G2V', 4),
('Sirius', 'A1V', 1), -- Sirius B is a white dwarf, but often referred to broadly as Sirius system
('Proxima Centauri', 'M5.5Ve', 3),
('Vega', 'A0V', 1),
('Betelgeuse', 'M1-M2 Ia-Iab', 0); -- Betelgeuse has no confirmed planets yet.

-- *** The Core Concept: JOINing Data ***
-- We often need to combine information from different tables.
-- For example, we might want to see Arcturian observations alongside related Pleiadian star chart data.
-- The JOIN clause is used to combine rows from two or more tables based on a related column between them.

-- We will use an INNER JOIN here, which returns only the rows where there is a match in both tables.
-- The ON clause specifies the condition for the join (i.e., which columns to match).

-- Example 1: Joining ArcturianLog with PleiadianStarChart
-- We want to see Arcturian observations for celestial bodies that are also in our Pleiadian star chart.
-- We join them on the 'celestial_body_designation' from ArcturianLog and 'system_name' from PleiadianStarChart.
SELECT
    al.timestamp,                      -- Arcturian observation timestamp
    al.celestial_body_designation,     -- The celestial body observed by Arcturians
    al.observation_notes,              -- Arcturian notes about the observation
    psc.primary_star_type,             -- Type of the star from Pleiadian chart
    psc.number_of_planets              -- Number of planets in that system from Pleiadian chart
FROM
    ArcturianLog AS al -- Alias 'al' for ArcturianLog to make the query shorter and clearer.
INNER JOIN
    PleiadianStarChart AS psc -- Alias 'psc' for PleiadianStarChart.
ON
    al.celestial_body_designation = psc.system_name; -- The condition to link the tables. We match when the designation is the same as the system name.

-- *** Filtering Combined Data with WHERE ***
-- Once we have joined the data, we can filter it further to find specific messages or patterns.
-- The WHERE clause is used to extract only those records that fulfill a specified condition.

-- Example 2: Finding specific messages about habitable zones from a particular species and filtering by star type.
-- We want to find Arcturian observations related to 'Proxima Centauri' that are in a system with a specific star type.
-- We are combining information from ArcturianLog and PleiadianStarChart, and then filtering the result.
SELECT
    al.timestamp,
    al.celestial_body_designation,
    al.observation_notes,
    psc.primary_star_type
FROM
    ArcturianLog AS al
INNER JOIN
    PleiadianStarChart AS psc ON al.celestial_body_designation = psc.system_name
WHERE
    al.celestial_body_designation = 'Proxima Centauri' -- Filter to only include observations about Proxima Centauri.
    AND psc.primary_star_type LIKE 'M%' -- Filter to include systems where the primary star type starts with 'M' (like M-dwarfs).
    AND al.observation_notes LIKE '%habitable zone%'; -- Filter Arcturian notes for mentions of "habitable zone".

-- Example 3: Deciphering messages by linking different log types.
-- Let's try to find Sirian communication fragments that occurred around the same time as Arcturian observations,
-- and that mention celestial bodies that are also in the Pleiadian Star Chart.
-- This involves joining three tables!
SELECT
    al.timestamp AS arcturian_observation_time,
    al.celestial_body_designation,
    al.observation_notes,
    st.event_timestamp AS sirian_event_time,
    st.communication_fragment,
    st.sender_species,
    psc.system_name,
    psc.primary_star_type
FROM
    ArcturianLog AS al
INNER JOIN
    SirianTranscript AS st ON al.timestamp = st.event_timestamp -- Link Arcturian logs to Sirian transcripts based on event time.
INNER JOIN
    PleiadianStarChart AS psc ON al.celestial_body_designation = psc.system_name -- Link Arcturian observations to Pleiadian star data by celestial body name.
WHERE
    st.sender_species = 'Pleiadian' -- We are interested in messages sent by Pleiadians.
    AND al.celestial_body_designation = 'Alpha Centauri'; -- And that are related to the Alpha Centauri system.

-- *** Example Usage and Learning Application ***

-- Imagine we want to find any decoded messages (SirianTranscript) that correspond to Arcturian observations
-- of 'Sirius B' and check if that star system has any planets recorded in the PleiadianStarChart.

SELECT
    al.timestamp,
    al.celestial_body_designation,
    al.observation_notes,
    st.communication_fragment,
    psc.number_of_planets
FROM
    ArcturianLog AS al
INNER JOIN
    SirianTranscript AS st ON al.timestamp = st.event_timestamp
INNER JOIN
    PleiadianStarChart AS psc ON al.celestial_body_designation = psc.system_name
WHERE
    al.celestial_body_designation = 'Sirius B'
    AND st.sender_species != 'Arcturian'; -- We want communications NOT from Arcturians themselves about Sirius B.

-- This query will return rows where:
-- 1. An Arcturian log entry matches a Sirian transcript entry by timestamp.
-- 2. The celestial body mentioned in the Arcturian log ('Sirius B') is found in the Pleiadian star chart.
-- 3. The celestial body designation from ArcturianLog is identical to the system_name in PleiadianStarChart.
-- 4. The communication fragment is not from the Arcturian species.

-- This demonstrates how JOINs allow us to stitch together pieces of information from different sources,
-- and how WHERE clauses help us to isolate the specific data we are looking for to decode alien messages.
-- By mastering JOINs and WHERE, you can unlock complex patterns hidden within disparate data logs.